const lang = {
    search_keyword: 'Suchbegriff',
    search_show_more: 'Mehr anzeigen...',
    username: 'Benutzername',
    password: 'Kennwort',
    btn_login: 'Einloggen',
    btn_logout: 'Ausloggen',
    login_text: 'Bitte einen Benutzernamen wählen. Beim Hinzufügen von neuen Inhalten wird dieser praktischerweise erwähnt.',
    label_username: 'Hi',
    label_location: 'Standort:',
    label_lat: 'Breitengrad',
    label_lng: 'Längengrad',
    btn_show_on_map: 'Auf Karte zeigen',
    btn_show_on_maps: 'In Google Maps öffnen',
    btn_show_on_web: 'Webseite öffnen',
    add_event_here: 'Hier Event hinzufügen',
    add_group_here: 'Hier Gruppe hinzufügen',
    add_spot_here: 'Hier Spot hinzufügen',
    form_name: 'Name',
    form_description: 'Beschreibung',
    form_category: 'Kategorie',
    form_features: 'Merkmale',
    form_images: 'Bilder',
    label_complete_later: 'Weitere Details können nach dem Speichern ergänzt werden.',
    btn_edit: 'Bearbeiten',
    btn_save: 'Speichern',
    btn_delete: 'Entwurf löschen',
    locate: 'Standort über GPS suchen',
    btn_members: 'Mitglieder',
    btn_events: 'Veranstaltungen',
    btn_spots: 'Spots',
    btn_groups: 'Gruppen',
    btn_articles: 'Artikel',
    btn_moves: 'Bewegungen',
    btn_videos: 'Videos',
    btn_help: 'Hilfe',
    no_title: 'Keine Überschrift vorhanden',
    no_body: 'Keine Beschreibung vorhanden.',
    no_images: 'Keine Bilder vorhanden.',
    no_geo: 'Keine Standortangabe vorhanden.',
    no_results_found: 'Keine Ergebnisse gefunden.',
    in_progress: 'In Arbeit...',
    error_server_request: 'Unerwartete Fehlermeldung vom Server.',
    error_load_spotmap: 'Spots konnten nicht aktualisiert werden.',
    error_load_spot: 'Spot konnte nicht geladen werden.',
    error_login: 'Benutzerdaten fehlerhaft',
    error_login_required: 'Um neue Spots hinzufügen, bitte erst einen Benutzernamen im 👤 Reiter wählen.',
    error_forbidden: 'Bitte erst einloggen.',
    error_add_node: 'Der neue Inhalt konnte nicht gespeichert werden.',
    error_geocode: 'Adresssuche:',
    spot: 'Spot',
    event: 'Event',
    group: 'Gruppe',
    new_marker: 'Hier neu hinzufügen',
    new_spot: 'Neuer Spot',
    new_group: 'Neue Gruppe',
    new_event: 'Neues Event',
    zoom: 'Karte vergrößern, um neuen Inhalt hinzuzufügen',
    position: 'Position',
    draft_saved: 'Der Text bleibt im Hintergrund gespeichert.',
    draft_restored: 'Der Entwurf wurde wiederhergestellt.',
    draft_delete_confirm: 'Der Entwurf wird hiermit gelöscht!\nWirklich fortfahren?',
    draft_deleted: 'Der Entwurf wurde gelöscht.',
    node_added: 'Danke!',
    node_created_by: 'erstellt von \\1',
    node_created_by_at: 'am \\1',
    node_created_at: 'erstellt am \\1',
    node_changed_at: ', geändert am \\1',
    node_changed_by: ', geändert von \\1',
    node_changed_by_at: 'am \\1',
    logged_in_as: 'Eingeloggt als \\1',
    type_spot: 'Spot',
    type_event: 'Event',
    type_group: 'Gruppe',
    type_move: 'Bewegung',
    type_page: 'Seite',
    type_post: 'Beitrag',
    spot_type_outdoor: 'Outdoor-Spot',
    spot_type_gym: 'Turnhalle',
    spot_type_parkourpark: 'Parkourpark',
    spot_type_parkourgym: 'Parkourhalle',
    spot_type_climbinggym: 'Kletterhalle',
    spot_type_pool: 'Schwimmbad',
    spot_type_cliff: 'Klippe',
    event_type_training: 'Training',
    event_type_workshop: 'Workshop',
    event_type_jam: 'Jam',
    event_type_trip: 'Reisen',
    event_type_competition: 'Wettbewerb',
    group_type_private: 'Private Person',
    group_type_community: 'Community',
    group_type_club: 'Verein',
    group_type_company: 'Firma',
    move_type_moves: 'Bewegung',
    move_type_conditioning: 'Konditionierung',
    move_type_games: 'Spiel',
    move_type_jumps: 'Sprung & Landung',
    move_type_vaults: 'Vault',
    move_type_bar: 'Stangenmove',
    move_type_flips: 'Salto & Schraube',
    move_type_combinations: 'Kombination',
    move_type_freezes: 'Freeze',
    move_type_beginner: 'Anfänger',
    move_type_intermediate: 'Mittelschwer',
    move_type_advanced: 'Fortgeschritten',
    spot_feature_covered: 'Überdacht (kein Regen)',
    spot_feature_bars: 'Stangen / Gerüst',
    spot_feature_walls: 'Wände',
    spot_feature_forest: 'Wald',
    spot_feature_pit: 'Weiche Sprunggrube',
    spot_feature_nightspot: 'Nachts beleuchtet',
    spot_feature_mindspot: 'Mindspot (Klettern, Schluchten)',
    spot_feature_view: 'Aussichtsplattform / schöne Bilder',
    spot_feature_playground: 'Spielplatz'
};

