var lang = {
    search_keyword: 'Clés de rechercher',
    search_show_more: 'Show more...',
    username: 'Nom d\'utilisateur',
    btn_logout: 'Se déconnecter',
    login_text: 'Please choose a username. If you add new content, your username will be mentioned conveniently.',
    label_username: 'Salut',
    label_location: 'Lieu:',
    label_lat: 'Latitude',
    label_lng: 'Longitude',
    btn_show_on_map: 'Montrer dans la carte',
    btn_show_on_maps: 'Ouvrir dans Google Maps',
    add_event_here: 'add event here',
    add_group_here: 'add group here',
    add_spot_here: 'add spot here',
    form_name: 'Nom',
    form_description: 'Description',
    form_category: 'Category',
    form_features: 'Features',
    form_images: 'Images',
    label_complete_later: 'Plus de détails peuvent être ajoutés après l\'enregistrement.',
    btn_edit: 'Edit',
    btn_save: 'Enregistrer',
    btn_delete: 'Effacer l\'ébauche',
    locate: 'trouver par GPS',
    btn_events: 'Events',
    btn_spots: 'Spots',
    btn_groups: 'Groups',
    btn_articles: 'Articles',
    btn_moves: 'Moves',
    btn_videos: 'Videos',
    btn_help: 'Help',
    no_results_found: 'No results found.',
    in_progress: 'In Progress...',
    error_server_request: 'Message d\'erreur inattendue du serveur.',
    error_load_spotmap: 'Ne peux pas mettre à jour les broches.',
    error_load_spot: 'Ne peux pas ouvrir ce spot.',
    error_login_required: 'To add new spots, please choose a username first at the 👤 tab.',
    error_forbidden: 'Please login first.',
    error_add_node: 'Ne peux pas enregistrer ce spot.',
    error_geocode: 'Address search:',
    spot: 'Spot',
    event: 'Event',
    group: 'Groupe',
    new_marker: 'Ajouter nouveau contenu ici',
    new_spot: 'Nouveau spot',
    new_group: 'Nouvelle groupe',
    new_event: 'Nouveau event',
    zoom: 'Zoom plus pour ajouter nouveau contenu',
    position: 'Position',
    draft_saved: 'L\'ébauche reste assuré à l\'arrière-plan.',
    draft_restored: 'L\'ébauche est restauré.',
    draft_delete_confirm: 'Vous effacez l\'ébauche!\nContiuner?',
    draft_deleted: 'L\'ébauche est effacé.',
    node_added: 'Merci!',
    node_created_by: 'created by \\1',
    node_created_by_at: 'on \\1',
    node_created_at: 'created on \\1',
    node_changed_at: ', changed on \\1',
    node_changed_by: ', changed by \\1',
    node_changed_by_at: 'on \\1',
    logged_in_as: 'Se connecté comme \\1',
    type_spot: 'Spot',
    type_event: 'Event',
    type_group: 'Group',
    type_move: 'Move',
    type_page: 'Page',
    type_post: 'Post',
    spot_type_outdoor: 'Outdoor spot',
    spot_type_gym: 'Gym',
    spot_type_parkourpark: 'Parkour park',
    spot_type_parkourgym: 'Parkour gym',
    spot_type_climbinggym: 'Climbing gym',
    spot_type_pool: 'Swimming pool',
    spot_type_cliff: 'Cliff',
    event_type_training: 'Training',
    event_type_workshop: 'Workshop',
    event_type_jam: 'Jam',
    event_type_trip: 'Travel',
    event_type_competition: 'Competition',
    group_type_private: 'Private Person',
    group_type_community: 'Community',
    group_type_club: 'Club',
    group_type_company: 'Company',
    move_type_moves: 'Move',
    move_type_conditioning: 'Conditioning',
    move_type_games: 'Game',
    move_type_jumps: 'Jump & Landing',
    move_type_vaults: 'Vault',
    move_type_bar: 'Bar move',
    move_type_flips: 'Flip & Spin',
    move_type_combinations: 'Combination',
    move_type_freezes: 'Freeze',
    move_type_beginner: 'beginner',
    move_type_intermediate: 'moderate',
    move_type_advanced: 'advanced',
    spot_feature_covered: 'Covered (no rain)',
    spot_feature_bars: 'bars / scaffolding',
    spot_feature_walls: 'walls',
    spot_feature_forest: 'forest',
    spot_feature_pit: 'soft landing pit',
    spot_feature_nightspot: 'light in the night',
    spot_feature_mindspot: 'mindspot (climbing, gaps)',
    spot_feature_view: 'viewing platform / nice pictures',
    spot_feature_playground: 'playground'
};