CREATE TABLE `spot` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `type` varchar(31) NOT NULL,
  `category` varchar(400) NOT NULL,
  `title` varchar(255) NOT NULL,
  `created` int(11) NOT NULL,
  `changed` int(11) NOT NULL,
  `lat` decimal(18,12) NOT NULL,
  `lng` decimal(18,12) NOT NULL,
  `geohash` varchar(16) NOT NULL,
  `zoom` tinyint(4) NOT NULL DEFAULT '-1',
  `p0` varchar(150) NOT NULL,
  `description` longtext NOT NULL,
  `user_id` int(10) NOT NULL DEFAULT '1',
  `url_alias` varchar(255) NOT NULL,
  `user_created` varchar(255) DEFAULT 'anonymous',
  `user_changed` varchar(255) DEFAULT 'anonymous',
  PRIMARY KEY (`zoom`,`id`),
  KEY `category` (`category`(333)),
  KEY `created` (`created`),
  KEY `changed` (`changed`),
  KEY `lat` (`lat`),
  KEY `lng` (`lng`),
  KEY `geohash` (`geohash`),
  KEY `filter` (`zoom`,`geohash`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;